### ISSUE TITLE
[Tracking] Bootstrap/Automation

### ISSUE THREAD

**Issue by alxbl** [alxbl/lab#19]
The following still needs to be automated:
- [ ] DynamicDNS updates
- [ ] istio-inject label injection
- [ ] zfs pool detection, provisioning and/or importing
- [ ] provision secrets from `/mnt/secrets`
- [ ] calico/istio integration
  - [ ] calico configmap [patching for istio policy][1]
  - [ ] istio config map [for dikaste][2]

[1]:  https://docs.tigera.io/calico/latest/network-policy/istio/app-layer-policy#enable-application-layer-policy
[2]: https://docs.tigera.io/calico/latest/network-policy/istio/app-layer-policy#update-istio-sidecar-injector
